<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Bitenovac.CloudBuild.Unit.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3.mtp-v2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\tools\Bitenovac.CloudBuild\Bitenovac.CloudBuild.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Build" ExcludeAssets="runtime"/>
        <PackageReference Include="Microsoft.Build.Utilities.Core" ExcludeAssets="runtime"/>
    </ItemGroup>

</Project>
