<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsLibrary>true</IsLibrary>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Bitenovac.DecompressionAlgorithms.Core\Bitenovac.DecompressionAlgorithms.Core.csproj"/>
        <ProjectReference Include="..\Bitenovac.DecompressionAlgorithms.Units\Bitenovac.DecompressionAlgorithms.Units.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Bitenovac.DecompressionAlgorithms.BuhlmannZhl16c.Unit.Tests"/>
    </ItemGroup>

</Project>
