<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Bitenovac.DecompressionAlgorithms.Core.Unit.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3.mtp-v2"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\src\libraries\Bitenovac.DecompressionAlgorithms.Core\Bitenovac.DecompressionAlgorithms.Core.csproj" />
    </ItemGroup>

</Project>
