<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>Bitenovac.CloudBuild</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Bitenovac.CloudBuild.Core\Bitenovac.CloudBuild.Core.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Build.Locator"/>
        <PackageReference Include="Microsoft.Build" ExcludeAssets="runtime"/>
        <PackageReference Include="Microsoft.Build.Utilities.Core" ExcludeAssets="runtime"/>
    </ItemGroup>

</Project>
